# Generated by Django 2.1.7 on 2019-04-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('image_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('image_path', models.CharField(max_length=200)),
                ('alphanumeric', models.CharField(blank=True, max_length=1, null=True)),
                ('object', models.CharField(blank=True, max_length=100, null=True)),
                ('alphanumeric_color', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_color', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
